from __future__ import annotations


SOURCE_CATALOG = (
    {
        "source_key": "eu-study-in-europe",
        "source_name": "Study in Europe",
        "base_url": "https://education.ec.europa.eu/study-in-europe",
        "country": "European Union",
        "region": "Europe",
        "fetcher_kind": "tinyfish",
        "official": True,
        "enabled": True,
    },
    {
        "source_key": "germany-daad",
        "source_name": "DAAD",
        "base_url": "https://www.daad.de/",
        "country": "Germany",
        "region": "Europe",
        "fetcher_kind": "tinyfish",
        "official": True,
        "enabled": True,
    },
    {
        "source_key": "france-eiffel",
        "source_name": "France Excellence Eiffel Scholarship",
        "base_url": "https://www.campusfrance.org/en/france-excellence-eiffel-scholarship-program",
        "country": "France",
        "region": "Europe",
        "fetcher_kind": "tinyfish",
        "official": True,
        "enabled": True,
    },
    {
        "source_key": "sweden-si",
        "source_name": "Swedish Institute Scholarships",
        "base_url": "https://si.se/en/apply/scholarships/swedish-institute-scholarships-for-global-professionals/",
        "country": "Sweden",
        "region": "Europe",
        "fetcher_kind": "tinyfish",
        "official": True,
        "enabled": True,
    },
    {
        "source_key": "ireland-goi-ies",
        "source_name": "Government of Ireland International Education Scholarships",
        "base_url": "https://hea.ie/policy/internationalisation/goi-ies/",
        "country": "Ireland",
        "region": "Europe",
        "fetcher_kind": "tinyfish",
        "official": True,
        "enabled": True,
    },
    {
        "source_key": "italy-study-in-italy",
        "source_name": "Study in Italy",
        "base_url": "https://studyinitaly.esteri.it",
        "country": "Italy",
        "region": "Europe",
        "fetcher_kind": "tinyfish",
        "official": True,
        "enabled": True,
    },
    {
        "source_key": "austria-grants-at",
        "source_name": "Grants.at",
        "base_url": "https://grants.at/en/",
        "country": "Austria",
        "region": "Europe",
        "fetcher_kind": "tinyfish",
        "official": True,
        "enabled": True,
    },
    {
        "source_key": "uk-chevening",
        "source_name": "Chevening",
        "base_url": "https://www.chevening.org/",
        "country": "United Kingdom",
        "region": "United Kingdom",
        "fetcher_kind": "tinyfish",
        "official": True,
        "enabled": True,
    },
    {
        "source_key": "uk-commonwealth",
        "source_name": "Commonwealth Scholarships",
        "base_url": "https://cscuk.fcdo.gov.uk/",
        "country": "United Kingdom",
        "region": "United Kingdom",
        "fetcher_kind": "tinyfish",
        "official": True,
        "enabled": True,
    },
    {
        "source_key": "uk-great",
        "source_name": "GREAT Scholarships",
        "base_url": "https://study-uk.britishcouncil.org/scholarships-funding/great-scholarships",
        "country": "United Kingdom",
        "region": "United Kingdom",
        "fetcher_kind": "tinyfish",
        "official": True,
        "enabled": True,
    },
    {
        "source_key": "usa-fulbright",
        "source_name": "Fulbright Foreign Student Program",
        "base_url": "https://foreign.fulbrightonline.org/",
        "country": "United States",
        "region": "North America",
        "fetcher_kind": "tinyfish",
        "official": True,
        "enabled": True,
    },
    {
        "source_key": "usa-educationusa",
        "source_name": "EducationUSA",
        "base_url": "https://educationusa.state.gov/",
        "country": "United States",
        "region": "North America",
        "fetcher_kind": "tinyfish",
        "official": True,
        "enabled": True,
    },
    {
        "source_key": "canada-educanada",
        "source_name": "EduCanada",
        "base_url": "https://www.educanada.ca/",
        "country": "Canada",
        "region": "North America",
        "fetcher_kind": "tinyfish",
        "official": True,
        "enabled": True,
    },
    {
        "source_key": "canada-vanier",
        "source_name": "Vanier Canada Graduate Scholarships",
        "base_url": "https://vanier.gc.ca/",
        "country": "Canada",
        "region": "North America",
        "fetcher_kind": "tinyfish",
        "official": True,
        "enabled": True,
    },
    {
        "source_key": "australia-awards",
        "source_name": "Australia Awards",
        "base_url": "https://australiaawards.com.au/",
        "country": "Australia",
        "region": "Australia",
        "fetcher_kind": "tinyfish",
        "official": True,
        "enabled": True,
    },
    {
        "source_key": "australia-dfat",
        "source_name": "DFAT Australia Awards",
        "base_url": "https://www.dfat.gov.au/people-to-people/australia-awards/",
        "country": "Australia",
        "region": "Australia",
        "fetcher_kind": "tinyfish",
        "official": True,
        "enabled": True,
    },
    {
        "source_key": "australia-rtp",
        "source_name": "Research Training Program",
        "base_url": "https://www.education.gov.au/research-block-grants/research-training-program",
        "country": "Australia",
        "region": "Australia",
        "fetcher_kind": "tinyfish",
        "official": True,
        "enabled": True,
    },
    {
        "source_key": "australia-study-australia",
        "source_name": "Study Australia",
        "base_url": "https://www.studyaustralia.gov.au/",
        "country": "Australia",
        "region": "Australia",
        "fetcher_kind": "tinyfish",
        "official": True,
        "enabled": True,
    },
    {
        "source_key": "uae-mohesr",
        "source_name": "UAE Ministry of Higher Education",
        "base_url": "https://www.mohesr.gov.ae/",
        "country": "United Arab Emirates",
        "region": "GCC",
        "fetcher_kind": "tinyfish",
        "official": True,
        "enabled": True,
    },
    {
        "source_key": "uae-khalifa",
        "source_name": "Khalifa University",
        "base_url": "https://www.ku.ac.ae/",
        "country": "United Arab Emirates",
        "region": "GCC",
        "fetcher_kind": "tinyfish",
        "official": True,
        "enabled": True,
    },
    {
        "source_key": "uae-mbzuai",
        "source_name": "MBZUAI",
        "base_url": "https://mbzuai.ac.ae/",
        "country": "United Arab Emirates",
        "region": "GCC",
        "fetcher_kind": "tinyfish",
        "official": True,
        "enabled": True,
    },
    {
        "source_key": "saudi-moe",
        "source_name": "Saudi Ministry of Education",
        "base_url": "https://moe.gov.sa/",
        "country": "Saudi Arabia",
        "region": "GCC",
        "fetcher_kind": "tinyfish",
        "official": True,
        "enabled": True,
    },
    {
        "source_key": "qatar-scholarships",
        "source_name": "Qatar Scholarships",
        "base_url": "https://www.qatarscholarships.qa/",
        "country": "Qatar",
        "region": "GCC",
        "fetcher_kind": "tinyfish",
        "official": True,
        "enabled": True,
    },
    {
        "source_key": "kuwait-mohe",
        "source_name": "Kuwait Ministry of Higher Education",
        "base_url": "https://kuwaitculture.com/mohe/",
        "country": "Kuwait",
        "region": "GCC",
        "fetcher_kind": "tinyfish",
        "official": True,
        "enabled": True,
    },
    {
        "source_key": "oman-heac",
        "source_name": "Oman HEAC",
        "base_url": "https://www.heac.gov.om/",
        "country": "Oman",
        "region": "GCC",
        "fetcher_kind": "tinyfish",
        "official": True,
        "enabled": True,
    },
    {
        "source_key": "oman-moheri",
        "source_name": "Oman Ministry of Higher Education",
        "base_url": "https://www.moheri.gov.om/",
        "country": "Oman",
        "region": "GCC",
        "fetcher_kind": "tinyfish",
        "official": True,
        "enabled": True,
    },
    {
        "source_key": "bahrain-moe",
        "source_name": "Bahrain Ministry of Education",
        "base_url": "https://moe.gov.bh/",
        "country": "Bahrain",
        "region": "GCC",
        "fetcher_kind": "tinyfish",
        "official": True,
        "enabled": True,
    },
    {
        "source_key": "bahrain-cpisp",
        "source_name": "CPISP Bahrain",
        "base_url": "https://www.cpisp.bh/",
        "country": "Bahrain",
        "region": "GCC",
        "fetcher_kind": "tinyfish",
        "official": True,
        "enabled": True,
    },
    {
        "source_key": "fastweb",
        "source_name": "Fastweb",
        "base_url": "https://www.fastweb.com/",
        "country": "Global",
        "region": "Aggregator",
        "fetcher_kind": "tinyfish",
        "official": False,
        "enabled": True,
    },
    {
        "source_key": "iefa",
        "source_name": "IEFA",
        "base_url": "https://www.iefa.org/",
        "country": "Global",
        "region": "Aggregator",
        "fetcher_kind": "tinyfish",
        "official": False,
        "enabled": True,
    },
)
