"""add profile fields

Revision ID: 5de282477048
Revises: 20260328_0002
Create Date: 2026-03-29 03:34:43.314787
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5de282477048'
down_revision = '20260328_0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('gender', sa.String(length=50), nullable=True))
    op.add_column('profiles', sa.Column('date_of_birth', sa.String(length=50), nullable=True))
    op.add_column('profiles', sa.Column('resume_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'resume_url')
    op.drop_column('profiles', 'date_of_birth')
    op.drop_column('profiles', 'gender')
    # ### end Alembic commands ###

