"""add_onboarding_completed

Revision ID: b86cef9c39c4
Revises: b47ae6fdebb3
Create Date: 2026-04-17 19:59:16.310628
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b86cef9c39c4'
down_revision = 'b47ae6fdebb3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'crawl_jobs', 'scholarship_sources', ['source_key'], ['source_key'])
    op.drop_constraint('uq_scholarships_scholarship_key', 'scholarships', type_='unique')
    op.drop_index('ix_scholarships_scholarship_key', table_name='scholarships')
    op.create_index(op.f('ix_scholarships_scholarship_key'), 'scholarships', ['scholarship_key'], unique=True)
    op.add_column('users', sa.Column('onboarding_completed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_completed')
    op.drop_index(op.f('ix_scholarships_scholarship_key'), table_name='scholarships')
    op.create_index('ix_scholarships_scholarship_key', 'scholarships', ['scholarship_key'], unique=False)
    op.create_unique_constraint('uq_scholarships_scholarship_key', 'scholarships', ['scholarship_key'])
    op.drop_constraint(None, 'crawl_jobs', type_='foreignkey')
    # ### end Alembic commands ###

