"""add_resume_metadata_fields

Revision ID: c7c3fe83272a
Revises: 20260417_0014
Create Date: 2026-05-10 17:25:54.643492
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7c3fe83272a'
down_revision = '20260417_0014'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('resume_is_accessible', sa.Boolean(), nullable=True))
    op.add_column('profiles', sa.Column('resume_format', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'resume_format')
    op.drop_column('profiles', 'resume_is_accessible')
    # ### end Alembic commands ###

