from __future__ import annotations

from scholr_crawler.models import FetcherKind, ScholarshipSource


SOURCES: tuple[ScholarshipSource, ...] = (
    ScholarshipSource(
        key="eu-study-in-europe",
        name="Study in Europe",
        base_url="https://education.ec.europa.eu/study-in-europe",
        country="European Union",
        region="Europe",
        tags=("official", "study-portal", "europe"),
    ),
    ScholarshipSource(
        key="germany-daad",
        name="DAAD",
        base_url="https://www.daad.de/",
        country="Germany",
        region="Europe",
        tags=("official", "government", "masters", "phd"),
    ),
    ScholarshipSource(
        key="france-eiffel",
        name="France Excellence Eiffel Scholarship",
        base_url="https://www.campusfrance.org/en/france-excellence-eiffel-scholarship-program",
        country="France",
        region="Europe",
        tags=("official", "government", "masters", "phd"),
    ),
    ScholarshipSource(
        key="sweden-si",
        name="Swedish Institute Scholarships",
        base_url="https://si.se/en/apply/scholarships/swedish-institute-scholarships-for-global-professionals/",
        country="Sweden",
        region="Europe",
        tags=("official", "government", "masters"),
    ),
    ScholarshipSource(
        key="ireland-goi-ies",
        name="Government of Ireland International Education Scholarships",
        base_url="https://hea.ie/policy/internationalisation/goi-ies/",
        country="Ireland",
        region="Europe",
        tags=("official", "government"),
    ),
    ScholarshipSource(
        key="italy-study-in-italy",
        name="Study in Italy",
        base_url="https://studyinitaly.esteri.it",
        country="Italy",
        region="Europe",
        tags=("official", "government"),
    ),
    ScholarshipSource(
        key="austria-grants-at",
        name="Grants.at",
        base_url="https://grants.at/en/",
        country="Austria",
        region="Europe",
        tags=("official", "government", "portal"),
    ),
    ScholarshipSource(
        key="uk-chevening",
        name="Chevening",
        base_url="https://www.chevening.org/",
        country="United Kingdom",
        region="United Kingdom",
        tags=("official", "government", "masters"),
    ),
    ScholarshipSource(
        key="uk-commonwealth",
        name="Commonwealth Scholarships",
        base_url="https://cscuk.fcdo.gov.uk/",
        country="United Kingdom",
        region="United Kingdom",
        tags=("official", "government", "masters", "phd"),
    ),
    ScholarshipSource(
        key="uk-great",
        name="GREAT Scholarships",
        base_url="https://study-uk.britishcouncil.org/scholarships-funding/great-scholarships",
        country="United Kingdom",
        region="United Kingdom",
        tags=("official", "government", "masters"),
    ),
    ScholarshipSource(
        key="usa-fulbright",
        name="Fulbright Foreign Student Program",
        base_url="https://foreign.fulbrightonline.org/",
        country="United States",
        region="North America",
        tags=("official", "government", "masters", "phd"),
    ),
    ScholarshipSource(
        key="usa-educationusa",
        name="EducationUSA",
        base_url="https://educationusa.state.gov/",
        country="United States",
        region="North America",
        tags=("official", "government", "portal"),
    ),
    ScholarshipSource(
        key="canada-educanada",
        name="EduCanada",
        base_url="https://www.educanada.ca/",
        country="Canada",
        region="North America",
        tags=("official", "government", "portal"),
    ),
    ScholarshipSource(
        key="canada-vanier",
        name="Vanier Canada Graduate Scholarships",
        base_url="https://vanier.gc.ca/",
        country="Canada",
        region="North America",
        tags=("official", "government", "phd"),
    ),
    ScholarshipSource(
        key="australia-awards",
        name="Australia Awards",
        base_url="https://australiaawards.com.au/",
        country="Australia",
        region="Australia",
        tags=("official", "government"),
    ),
    ScholarshipSource(
        key="australia-dfat",
        name="DFAT Australia Awards",
        base_url="https://www.dfat.gov.au/people-to-people/australia-awards/",
        country="Australia",
        region="Australia",
        tags=("official", "government"),
    ),
    ScholarshipSource(
        key="australia-rtp",
        name="Research Training Program",
        base_url="https://www.education.gov.au/research-block-grants/research-training-program",
        country="Australia",
        region="Australia",
        tags=("official", "government", "phd", "research"),
    ),
    ScholarshipSource(
        key="australia-study-australia",
        name="Study Australia",
        base_url="https://www.studyaustralia.gov.au/",
        country="Australia",
        region="Australia",
        tags=("official", "government", "portal"),
    ),
    ScholarshipSource(
        key="uae-mohesr",
        name="UAE Ministry of Higher Education",
        base_url="https://www.mohesr.gov.ae/",
        country="United Arab Emirates",
        region="GCC",
        tags=("official", "government"),
    ),
    ScholarshipSource(
        key="uae-khalifa",
        name="Khalifa University",
        base_url="https://www.ku.ac.ae/",
        country="United Arab Emirates",
        region="GCC",
        tags=("official", "university", "masters", "phd"),
    ),
    ScholarshipSource(
        key="uae-mbzuai",
        name="MBZUAI",
        base_url="https://mbzuai.ac.ae/",
        country="United Arab Emirates",
        region="GCC",
        tags=("official", "university", "masters", "phd", "ai"),
    ),
    ScholarshipSource(
        key="saudi-moe",
        name="Saudi Ministry of Education",
        base_url="https://moe.gov.sa/",
        country="Saudi Arabia",
        region="GCC",
        tags=("official", "government"),
    ),
    ScholarshipSource(
        key="qatar-scholarships",
        name="Qatar Scholarships",
        base_url="https://www.qatarscholarships.qa/",
        country="Qatar",
        region="GCC",
        tags=("official", "government"),
    ),
    ScholarshipSource(
        key="kuwait-mohe",
        name="Kuwait Ministry of Higher Education",
        base_url="https://kuwaitculture.com/mohe/",
        country="Kuwait",
        region="GCC",
        tags=("official", "government"),
    ),
    ScholarshipSource(
        key="oman-heac",
        name="Oman HEAC",
        base_url="https://www.heac.gov.om/",
        country="Oman",
        region="GCC",
        tags=("official", "government", "portal"),
    ),
    ScholarshipSource(
        key="oman-moheri",
        name="Oman Ministry of Higher Education",
        base_url="https://www.moheri.gov.om/",
        country="Oman",
        region="GCC",
        tags=("official", "government"),
    ),
    ScholarshipSource(
        key="bahrain-moe",
        name="Bahrain Ministry of Education",
        base_url="https://moe.gov.bh/",
        country="Bahrain",
        region="GCC",
        tags=("official", "government"),
    ),
    ScholarshipSource(
        key="bahrain-cpisp",
        name="CPISP Bahrain",
        base_url="https://www.cpisp.bh/",
        country="Bahrain",
        region="GCC",
        tags=("official", "government", "portal"),
    ),
    ScholarshipSource(
        key="fastweb",
        name="Fastweb",
        base_url="https://www.fastweb.com/",
        country="Global",
        region="Aggregator",
        official=False,
        tags=("aggregator", "private"),
        notes="Private aggregator; useful for discovery, lower trust than official sources.",
    ),
    ScholarshipSource(
        key="iefa",
        name="IEFA",
        base_url="https://www.iefa.org/",
        country="Global",
        region="Aggregator",
        official=False,
        tags=("aggregator", "private", "international"),
        notes="Private aggregator; treat as lead generation and verify against official pages.",
    ),
)


def list_sources(
    *,
    country: str | None = None,
    region: str | None = None,
    official_only: bool = False,
    enabled_only: bool = True,
) -> list[ScholarshipSource]:
    sources = list(SOURCES)
    if enabled_only:
        sources = [source for source in sources if source.enabled]
    if official_only:
        sources = [source for source in sources if source.official]
    if country:
        sources = [source for source in sources if source.country.lower() == country.lower()]
    if region:
        sources = [source for source in sources if source.region.lower() == region.lower()]
    return sources
